# devcontainers / codespaces
{ pkgs, lib, config, ... }:

{
  home = {
    username = "root";
    homeDirectory = "/root";

    packages = [
      pkgs.docker # on OSX docker/orbstack is installed by homebrew

      # Terminal capability database. ncurses is in the closure twice already,
      # but only as a transitive dependency of stdenv/the shell - its data files
      # are not part of the user environment, so nothing under a path ncurses
      # actually searches exists in this image: no /etc/terminfo, no
      # /lib/terminfo, no /usr/share/terminfo (those are the compiled-in
      # defaults, and they're all FHS paths the nixos/nix image doesn't
      # populate). `docker exec` then defaults TERM=xterm and everything
      # degrades quietly - broken alt-screen and scrollback, wrong colors,
      # mangled line-drawing, Ctrl/Shift+arrow arriving as garbage. It read for
      # a long time as "tmux is broken under cmux" (issue #116).
      #
      # Installing ncurses at profile level rather than in a devShell is
      # deliberate twice over: terminal capability is a property of the
      # environment, not of whichever repo happens to be mounted at /work; and
      # the profile is what a future non-root container user would still get,
      # where a ~/.terminfo fix would not follow.
      #
      # It also puts infocmp/tic/toe/tput on PATH, which is what makes the
      # failure diagnosable next time instead of invisible.
      pkgs.ncurses

      # Ghostty's own entry, so a host running Ghostty can pass its
      # TERM=xterm-ghostty straight in. ncurses 6.6 ships a `ghostty` entry but
      # NOT `xterm-ghostty`, and xterm-ghostty is the name Ghostty actually
      # exports (it prefixes with "xterm-" so capability-sniffing programs stop
      # guessing wrong).
      #
      # hiPrio because of that overlap: ncurses and ghostty.terminfo both
      # provide share/terminfo/g/ghostty, and two files at the same path is a
      # buildEnv collision that fails the build. This is the one collision shape
      # lib.hiPrio does fix - it's inside home-manager's own closure, not a
      # clash with the base image's nix-env profile (see the note on
      # `programs.bash.package` below). Ghostty's entry wins on the merits too:
      # the ncurses one is a third-party description of the terminal, this one
      # is generated by it.
      #
      # `.terminfo` is a real output of the ghostty derivation, so only that
      # output is substituted: 24KB and two files, with the GTK/zig closure
      # never fetched or built - which is the difference between this being
      # affordable on the 2012 MBP and not.
      #
      # And yes, hiPrio keeps the output selection, despite reading like it
      # can't: it goes through `overrideAttrs`, which returns a whole package,
      # but lib.extendDerivation gives every output its own overrideAttrs that
      # re-selects that output. Checked, because the failure mode would be
      # silently installing the entire ghostty app instead of two terminfo
      # files.
      (lib.hiPrio pkgs.ghostty.terminfo)
    ];

    # ...and point ncurses at where those entries land. TERMINFO_DIRS is
    # searched *before* the compiled-in FHS list rather than replacing it, so
    # this only adds. The profile symlink is the stable handle: it follows
    # generations, so it survives an ncurses bump, a home-manager switch, and
    # nix-collect-garbage - unlike the /nix/store/...-ncurses-6.6/share/terminfo
    # path that "fixes" this interactively and must never be committed.
    sessionVariables = {
      TERMINFO_DIRS = "${config.home.profileDirectory}/share/terminfo";
    };

    # Container-environment notes as a user-level Claude rule. ~/.claude/rules/
    # is discovered by Claude Code and loaded into every session on the machine
    # with no @import line, so this applies whatever is mounted at /work.
    #
    # This used to be copied over ~/.claude/CLAUDE.md by the Dockerfile and
    # again by docker/entrypoint.sh on every start. The entrypoint copy ran
    # before the *conditional* home-manager activation and wiped the managed
    # import block on every restart after the first. Owning the file through
    # the generation removes the copy, the shadowing problem the copy existed
    # to solve, and the clobber it caused.
    #
    # Arch is resolved at eval time: both "alyssa@dev" (aarch64-linux) and
    # "alyssa@dev-x86" (x86_64-linux) use this profile, so hostPlatform is the
    # same signal the Dockerfile's `uname -m` was reaching for.
    file.".claude/rules/container-env.md".source =
      if pkgs.stdenv.hostPlatform.isAarch64 then
        ../../docker/CLAUDE-arm64.md
      else
        ../../docker/CLAUDE.md;
  };

  # Configure bash, but do NOT ship a bash. common.nix enables programs.bash so
  # the container's fallback shell gets a prompt and direnv; that module also
  # puts bashInteractive into home.packages, which collides head-on with the
  # bash-interactive the nixos/nix base image already has in root's nix-env
  # profile. The two are different store paths, so assembling the user
  # environment dies with:
  #
  #   error: Unable to build profile. There is a conflict for the following files:
  #            ".../home-manager-path/bin/bash"
  #            ".../bash-interactive-5.3p9/bin/bash"
  #
  # and the whole activation fails at installPackages - AFTER linkGeneration has
  # already written the dotfiles, so you get a working prompt and a container
  # with no claude, no jj, no ripgrep. A confusing way to fail.
  #
  # `package = null` (the option is nullable) keeps every generated file -
  # ~/.bashrc, ~/.bash_profile, ~/.profile, and the starship + direnv hooks in
  # them - while leaving the binary to the base image. Configuring a shell and
  # installing one are separate concerns; here we only want the former.
  #
  # Scoped to this profile on purpose. The collision comes from the base image's
  # pre-populated nix-env profile, which is a container fact, not a Linux one.
  # The darwin profiles keep home-manager's bash deliberately: macOS ships bash
  # 3.2, and home-manager's own bashrc uses `[[ -v ]]`, which needs 4.2+.
  programs.bash.package = null;
}