# Charm's own packages, from charmbracelet/nur.
#
# Why a second source for something nixpkgs already has: nixpkgs' crush is
# bumped by hand, and crush ships faster than that. At the nixpkgs rev this
# flake locks, `crush` is 0.88.1 (tagged 2026-08-07) against 0.91.2 upstream
# (2026-08-26) - three feature releases - and nixpkgs *master* has the same
# 0.88.1 with no open bump PR. So `nix flake update` genuinely cannot close
# the gap: the newest nixpkgs there is to lock still has the old crush.
#
# charmbracelet/nur is Charm's own repo, not a volunteer's: every pkgs/*
# expression carries "generated by GoReleaser. DO NOT EDIT." and their
# release bot pushes the bump the same day each tag lands. It tracks upstream
# by construction rather than by someone remembering.
#
# Two deliberate narrowings:
#
#   - Scoped to `pkgs.charm-nur.<name>`, not spliced into the top level.
#     Upstream's overlays.default shadows *every* Charm attribute in nixpkgs
#     (glow, vhs, gum, ...). We install glow and vhs from core-packages and
#     both are already current in nixpkgs (3.0.0 / 0.11.0, identical to what
#     this repo would serve), so there is nothing to gain from swapping them
#     and a silent source->binary substitution to lose.
#
#   - The package only; not their home-manager module. `programs.crush` there
#     writes xdg.configFile."crush/crush.json", which is precisely the file
#     home-manager/modules/tools/crush.nix owns. Two modules, one path, one
#     activation conflict.
#
# Worth knowing: these are release *binaries* (fetchurl of the GoReleaser
# tarball, sourceProvenance = binaryNativeCode), not source builds. For crush
# that is a straight improvement - it is unfree (FSL-1.1-MIT), so
# cache.nixos.org holds nothing for the nixpkgs build and every machine
# compiled a Go program from scratch to get it. It still needs allowUnfree.
charmNur: final: _: {
  # charmbracelet/nur's overlay is `final: prev: import ./pkgs { pkgs = final; }`
  # - it ignores prev and builds its package set against whatever pkgs it is
  # handed. Applying it with our `final` for both arguments therefore yields
  # exactly that package set evaluated against *this* nixpkgs (crucially, with
  # our config.allowUnfree, which crush needs and their own flake's `packages`
  # output does not set), bound to one attribute instead of the top level.
  charm-nur = charmNur.overlays.default final final;
}
