name: Nix

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Nix Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Lint with statix
        run: |
          nix profile install nixpkgs#statix
          statix check .

      - name: Check for dead code
        run: |
          nix profile install nixpkgs#deadnix
          deadnix --fail .

  check:
    name: Validate Flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check flake
        run: nix flake check --all-systems

      - name: Show flake outputs
        run: nix flake show
